openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is the API documentation for Contacts App. The API allows users to manage contacts and perform various related operations.
tags:
  - name: Contacts
    description: Endpoints related to managing contacts.
  - name: Authentication
    description: Endpoints for user registration, login, and token management.
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://nodejs-hw-mongodb-yy6k.onrender.com
    description: Production server
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: ../swagger/components/schemas/Contact.yaml
    ContactInput:
      $ref: ../swagger/components/schemas/ContactInput.yaml
    User:
      $ref: ../swagger/components/schemas/User.yaml
  responses:
    NotFound:
      $ref: ../swagger/components/responses/NotFound.yaml
    BadRequest:
      $ref: ../swagger/components/responses/BadRequest.yaml
    Unauthorized:
      $ref: ../swagger/components/responses/Unauthorized.yaml
